export const properties = [
  {
    id: "1",
    title: "Premium 3 BHK Apartment",
    city: "Gurgaon",
    location: "Sector 65",
    type: "Apartment",
    purpose: "Buy",
    price: 18500000,
    bedrooms: 3,
    area: 1850,
    image: "/properties/property-1.jpg",
  },

  {
    id: "2",
    title: "Residential Plot",
    city: "Noida",
    location: "Sector 150",
    type: "Plot",
    purpose: "Buy",
    price: 7200000,
    bedrooms: 0,
    area: 1200,
    image: "/properties/property-3.jpg",
  },

  {
    id: "3",
    title: "Luxury Villa",
    city: "Bangalore",
    location: "Whitefield",
    type: "Villa",
    purpose: "Buy",
    price: 32500000,
    bedrooms: 4,
    area: 3200,
    image: "/properties/property-4.jpg",
  },

  {
    id: "4",
    title: "Modern 2 BHK Apartment",
    city: "Delhi",
    location: "Dwarka",
    type: "Apartment",
    purpose: "Rent",
    price: 35000,
    bedrooms: 2,
    area: 1250,
    image: "/properties/property-1.jpg",
  },

  {
    id: "5",
    title: "Independent House",
    city: "Gurgaon",
    location: "Sohna",
    type: "Independent House",
    purpose: "Buy",
    price: 9500000,
    bedrooms: 3,
    area: 2400,
    image: "/properties/property-5.jpg",
  },

  {
    id: "6",
    title: "Commercial Office Space",
    city: "Mumbai",
    location: "Andheri",
    type: "Commercial",
    purpose: "Rent",
    price: 125000,
    bedrooms: 0,
    area: 1800,
    image: "/properties/property-2.jpg",
  },
];